package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/gocomply/xsd2go/pkg/xsd2go"
	"github.com/urfave/cli"
)

func main() {
	app := cli.NewApp()
	app.Name = "GoComply XSD2Go"
	app.Usage = "Automatically generate golang xml parser based on XSD"
	app.Commands = []cli.Command{
		convert,
	}

	err := app.Run(os.Args)
	if err != nil {
		panic(err)
	}
}

var convert = cli.Command{
	Name:      "convert",
	Usage:     "convert XSD to golang code to parse xml files generated by given xsd",
	ArgsUsage: "XSD-FILE GO-MODULE-IMPORT OUTPUT-DIR",
	Before: func(c *cli.Context) error {
		inputs := c.StringSlice("input")
		if len(inputs) > 0 && c.NArg() > 2 {
			return cli.NewExitError("cannot specify both --input parameters and positional input argument", 1)
		} else if len(inputs) == 0 && c.NArg() != 3 {
			return cli.NewExitError("Exactly 3 arguments are required", 1)
		}

		for _, override := range c.StringSlice("xmlns-override") {
			if !strings.Contains(override, "=") {
				return cli.NewExitError(
					fmt.Sprintf("Invalid xmlns-override: '%s', expecting form of XMLNS=GOPKGNAME", override),
					1)
			}
		}

		for _, override := range c.StringSlice("type-override") {
			if !strings.Contains(override, "=") {
				return cli.NewExitError(
					fmt.Sprintf("Invalid type-override: '%s', expecting form of URI:TYPE=GOTYPE", override),
					1)
			}
		}

		return nil
	},
	Action: func(c *cli.Context) error {
		argOffset := 0
		inputs := c.StringSlice("input")
		if len(inputs) == 0 {
			// Use the single positional input argument.
			inputs = []string{c.Args()[0]}

			// The other positional arguments are expected after the input positional argument.
			argOffset += 1
		}
		goModule, outputDir := c.Args()[argOffset], c.Args()[argOffset+1]
		err := xsd2go.Convert(
			inputs,
			goModule,
			outputDir,
			c.StringSlice("xmlns-override"),
			c.StringSlice("type-override"),
		)

		if err != nil {
			return cli.NewExitError(err, 1)
		}
		return nil
	},
	Flags: []cli.Flag{
		cli.StringSliceFlag{
			Name:  "xmlns-override",
			Usage: "Allows to explicitly set gopackage name for given XMLNS. Example: --xmlns-override='http://www.w3.org/2000/09/xmldsig#=xml_signatures'",
		},
		cli.StringSliceFlag{
			Name:  "type-override",
			Usage: "Allows to override the Go type that the generator will use for the specified xml type. Example: --type-override='http://www.w3.org/2001/XMLSchema:IDREFS=myType'",
		},
		cli.StringSliceFlag{
			Name:  "input",
			Usage: "Input file. Example: --input='/path/to/file' --input='/path/to/files/*.xsd'",
		},
	},
}
