// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for https://simple.example.com/
package simple_schema

import (
	"encoding/xml"
)

// Element
type Myelement struct {
	XMLName xml.Name `xml:"myelement"`

	Id int64 `xml:"id"`

	ExternalId *int64 `xml:"external_id"`

	Id1 *int `xml:"id_1"`

	Id21 *int `xml:"id_21"`

	Id22 *int `xml:"id_22"`
}

// XSD ComplexType declarations

type MyElementType struct {
	XMLName xml.Name

	Id int64 `xml:"id"`

	ExternalId *int64 `xml:"external_id"`

	Id1 *int `xml:"id_1"`

	Id21 *int `xml:"id_21"`

	Id22 *int `xml:"id_22"`
}

// XSD SimpleType declarations
