name: Lint CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.24.x]

    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - run: go vet ./...

    - name: Ensure clean git
      run: |
        if [ "$(gofmt -s -l ./cli ./pkg ./tests | wc -l)" -gt 0 ]; then
            gofmt -s -l -d ./cli ./pkg ./tests
            echo "Please run: go fmt ./..."
            exit 1
        fi

        if [ "$(go mod tidy -v | wc -l)" -gt 0 ]; then
            go mod tidy -v
            echo "Please run: go mod tidy"
            exit 1
        fi

        if [[ -n $(git status -s) ]] ; then
          echo "Running 'go fmt' or 'go mod tidy' left git repo in a modified state."
          echo "Please ensure to include those changes in your PR"
          git status -s
          git diff
          exit 1
        fi

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        args: "--config=./.github/workflows/lint-golangci-lint.yaml"
