version: "2"
linters:
  settings:
    staticcheck:
      checks:
        - all
        - -SA5008
        - -ST1003
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    warn-unused: true # Log a warning when exclusion rule is unused
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
